kind: pipeline
type: docker
name: drone-docker-deploy-test

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
    - git clone ${DRONE_GITHUB_PROXY}/https://github.com/kobememory/drone-docker-deploy-demo
    - git checkout $DRONE_COMMIT
    
  - name: npm_build
    image: node:16.19.1-slim
    volumes:
      - name: node_modules # 数据卷名称
        path: /drone/src/node_modules # 容器内目录 绝对路径
    commands:
      - npm config set registry https://registry.npm.taobao.org
      - npm install
      - npm run build

  - name: docker_build
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t ${DRONE_REPO_NAME} .
      - if [ $(docker ps -aq --filter name=${DRONE_REPO_NAME}-c) ]; then docker stop ${DRONE_REPO_NAME}-c;fi
      - if [ $(docker ps -aq --filter name=${DRONE_REPO_NAME}-c -a) ]; then docker rm -f ${DRONE_REPO_NAME}-c;fi
      - docker run -d -p 8001:80 --name ${DRONE_REPO_NAME}-c --network docker_app_net ${DRONE_REPO_NAME}
      - docker image prune -f

trigger:
  branch:
    - dev
  event:
    - push

volumes:
  - name: node_modules
    host:
      path: /data/drone/drone-ci-demo/node_modules
  - name: dockersock
    host:
      path: /var/run/docker.sock