kind: pipeline
type: docker
name: drone-docker-deploy-test

steps:
  - name: npm_build
    image: node:16.19.1-slim
    volumes:
      - name: node_modules # 数据卷名称
        path: /drone/src/node_modules # 容器内目录 绝对路径
    commands:
      - npm config set registry https://registry.npm.taobao.org
      - npm install
      - npm run build

  - name: docker
    image: docker
    commands: 
      - docker-compose -v
    # commands:
    #   - docker build -t ${DRONE_REPO_NAME} .
    #   - docker run -d -p 80:80 --name ${DRONE_REPO_NAME}-c ${DRONE_REPO_NAME}
    #   - docker image prune -f

trigger:
  branch:
    - dev
  event:
    - push

volumes:
  - name: node_modules
    host:
      path: /data/drone/drone-ci-demo/node_modules
  - name: dockersock
    host:
      path: /var/run/docker.sock