name: Deploy to Aliyun Server

on:
  push:
    branches:
      - dev

env:
  DOCKER_NAMESPACE: lankobe
  BASE_IMAGE_NAME: vue3_github_action_docker_deploy_demo
  DOCKER_PORT: 9099

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      # 定义环境变量
      - name: Set env
        run: |
          echo "IMAGE_TAG=${{ secrets.ALIYUN_DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${{ env.BASE_IMAGE_NAME}}:${{ github.sha }}" >> $GITHUB_ENV

      # 拉取指定分支代码
      - name: Checkout code
        uses: actions/checkout@v2
        
      # 配置node环境
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'npm'

      # 执行打包
      - name: Build
        run: |
          npm i
          npm run build
          
      # 设置docker环境
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录阿里云docker仓库
      - name: Login to Aliyun Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_DOCKER_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

      # 构建docker镜像并上传到阿里云镜像仓库
      - name: Build Image and push to aliyun docker registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ env.IMAGE_TAG }}

      # 登录阿里云服务器，拉取镜像并启动容器
      - name: Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.ALIYUN_RSA_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.ALIYUN_DOCKER_PASSWORD }} | docker login --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin ${{ secrets.ALIYUN_DOCKER_REGISTRY }}
            docker pull ${{ env.IMAGE_TAG }}
            if [ $(docker ps -aq --filter name=${{ BASE_IMAGE_NAME }}) ]; then docker stop ${{ BASE_IMAGE_NAME }};fi
            if [ $(docker ps -aq --filter name=${{ BASE_IMAGE_NAME }} -a) ]; then docker rm -f ${{ BASE_IMAGE_NAME }};fi
            docker container run -p ${{ DOCKER_PORT }}:80 -d --name ${BASE_IMAGE_NAME} ${BASE_IMAGE_NAME}:${{ env.IMAGE_TAG }}
            docker image prune -f
      

      # - name: Configure SSH keys
      #   env:
      #     PRIVATE_KEY: ${{ secrets.ALIYUN_RSA_PRIVATE_KEY }}
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan -H 121.43.33.219 >> ~/.ssh/known_hosts

      # - name: Deploy to Server
      #   run: |
      #     echo ${{ github.sha }}
